title = "Estland"

[[pages]]
id = 1
title = "Info"
content = """# Info

## Hauptstadt
Die Hauptstadt von **Estland** ist **Tallinn**.

## Flagge
![Flagge Estland](https://images.unsplash.com/photo-1508756530018-25b84612c5ff?auto=format&fit=crop&q=80&w=800 "Flagge Estland")

## Währung
Die **Währung** von **Estland** ist der **Euro** (seit 2011).

## Lage
**Estland** liegt südlich von **Finnland**. [**Hier auf der Karte**](https://maps.app.goo.gl/ae1pTE9LjXVJ8ccc9)

## Sprache
In **Estland** spricht man **Estnisch**."""