title = "Modern Documentation"

[[pages]]
id = 1
title = "Info"
content = """# Info

## Hauptstadt
Die Hauptstadt von **Estland** ist **Tallinn**.

## Flagge
![Flagge Estland](https://images.unsplash.com/photo-1508833577321-1d7c6367ad47?auto=format&fit=crop&q=80 "Flagge Estland")

## Währung
Die **Währung** von **Estland** ist der **Euro** (seit 2011).

## Lage
**Estland** liegt südlich von **Finnland**. ([**Hier**](https://maps.app.goo.gl/ae1pTE9LjXVJ8ccc9 "Hier"))

## Sprache
In **Estland** spricht man **Estnisch**."""