title = "Modern Documentation"

[[pages]]
id = 1
title = "Info"
content = """# Info

## Hauptstadt
Die Hauptstadt von **Estland** ist **Tallinn**.

## Flagge
![Flagge Estland](https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Flag_of_Estonia.svg/1200px-Flag_of_Estonia.svg.png)

## Währung
Die **Währung** von **Estland** ist der **Euro** (seit 2011).

## Lage
**Estland** liegt südlich von **Finnland**. ([**Hier**](https://maps.app.goo.gl/ae1pTE9LjXVJ8ccc9 "Hier"))

## Sprache
In **Estland** spricht man **Estnisch**."""